repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: trailing-whitespace

  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3.6

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.6.0
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        args:
          - -j 10
        files: ^tatsu_parser
        types: [python]
        require_serial: true

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.790
    hooks:
      - id: mypy
        stages: [push]
        files: ^tatsu_parser/
        language_version: python3.6

  - repo: local
    hooks:
      - id: pytest-cov-check
        name: pytest-cov-check
        entry: py.test --cov=tatsu_parser tests
        language: system
        pass_filenames: false
        always_run: true

  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
